-- Enrich resort descriptions with richer, factual, real-world detail.
-- V2/V4 seeded a single superficial sentence per resort; this migration replaces
-- each with a 2-4 sentence description built from well-established, verifiable facts
-- (location, elevation band, famous runs, Olympic/World Cup heritage, terrain
-- character and snow reputation). Only stable facts are used; where a precise
-- figure was uncertain, the wording stays qualitative rather than inventing numbers.
-- Idempotent-friendly: matches rows by unique slug and touches only description/updated_at.
SET search_path TO resorts, public;

-- ============================ EUROPE ============================
-- France
UPDATE resorts SET description = 'Set at 1,035 m beneath Mont Blanc (4,808 m) in the Haute-Savoie, Chamonix is a birthplace of alpine mountaineering and hosted the first Winter Olympics in 1924. Its lift-served terrain is split across separate sectors (Brevent-Flegere, Les Grands Montets, Le Tour), while the legendary Vallee Blanche glacier descent and the Aiguille du Midi cable car (3,842 m) draw serious off-piste skiers and alpinists from around the world.', updated_at = now() WHERE slug = 'chamonix-mont-blanc';
UPDATE resorts SET description = 'At around 2,300 m, Val Thorens is the highest ski resort in Europe and the top-altitude gateway to the Three Valleys (Les 3 Vallees), the largest linked ski area in the world with roughly 600 km of pistes. Its snow-sure, glacier-backed terrain, ski-in/ski-out village and the Cime Caron cable car make it a reliable early- and late-season destination.', updated_at = now() WHERE slug = 'val-thorens';
UPDATE resorts SET description = 'The most exclusive of the Three Valleys resorts, Courchevel rises through a series of villages from 1,300 m to 1,850 m above the Tarentaise valley. Known for immaculate grooming, an altiport for private planes and Michelin-starred dining, it offers wide sunny pistes plus steep couloirs off the Saulire, all part of the vast 600 km Trois Vallees network.', updated_at = now() WHERE slug = 'courchevel';
UPDATE resorts SET description = 'A high, snow-sure resort around 2,100 m linked with Val d''Isere to form the Espace Killy (about 300 km of pistes), Tignes offers year-round skiing on the Grande Motte glacier reached by an underground funicular. Its stark, purpose-built villages sit above the treeline and are prized for reliable snow deep into spring.', updated_at = now() WHERE slug = 'tignes';
UPDATE resorts SET description = 'A classic Tarentaise resort at 1,850 m, Val d''Isere joins Tignes in the Espace Killy and regularly hosts Alpine World Cup racing on the famous Face de Bellevarde, used at the 1992 Albertville Olympics. It combines a charming stone-built village with extensive, snow-sure high-altitude terrain.', updated_at = now() WHERE slug = 'val-disere';
UPDATE resorts SET description = 'One of France''s oldest resorts, Les 2 Alpes stretches from the village at 1,650 m up to 3,600 m on the Glacier du Mont-de-Lans, one of the largest skiable glaciers in Europe and a summer-skiing venue. It is known for a huge vertical drop, a lively village and freeride access toward neighbouring La Grave.', updated_at = now() WHERE slug = 'les-deux-alpes';
UPDATE resorts SET description = 'Nicknamed the "Island in the Sun" for its southern exposure and famous sunshine, Alpe d''Huez sits at 1,860 m in the Oisans and rises to the 3,330 m Pic Blanc. It is home to the Sarenne, at roughly 16 km one of the longest black runs in the world, and a large network of varied pistes.', updated_at = now() WHERE slug = 'alpe-dhuez';
UPDATE resorts SET description = 'Occupying the central valley of the Three Valleys at around 1,450-1,750 m, Meribel is the hub connecting Courchevel and Val Thorens across the 600 km network. Its wood-and-stone chalet architecture, protected by strict building codes, makes it a scenic base; it hosted alpine and ice-hockey events at the 1992 Olympics.', updated_at = now() WHERE slug = 'meribel';
UPDATE resorts SET description = 'A collection of high villages between about 1,800 and 2,100 m, La Plagne links to Les Arcs via the double-decker Vanoise Express cable car to form Paradiski, one of the world''s largest ski areas at around 425 km. It offers glacier skiing on Bellecote and hosted bobsleigh, luge and skeleton at the 1992 Albertville Games on France''s only Olympic sliding track.', updated_at = now() WHERE slug = 'la-plagne';
UPDATE resorts SET description = 'A purpose-built Paradiski resort above Bourg-Saint-Maurice, Les Arcs spans villages from 1,600 to 2,000 m and rises to the 3,226 m Aiguille Rouge, giving one of the biggest verticals in the Alps. It pioneered the "ski evolutif" teaching method and speed-skiing on the Aiguille Rouge, and links to La Plagne across roughly 425 km of pistes.', updated_at = now() WHERE slug = 'les-arcs';
UPDATE resorts SET description = 'An elegant, historic village developed by the Rothschild family in the 1920s as a French answer to St. Moritz, Megeve sits at around 1,100 m near Mont Blanc. Its cobbled medieval centre, horse-drawn sleighs and gentle tree-lined slopes across three linked massifs make it more about refined atmosphere than extreme terrain.', updated_at = now() WHERE slug = 'megeve';
UPDATE resorts SET description = 'A car-free, ski-in/ski-out resort at 1,800 m built in distinctive angular timber-clad architecture, Avoriaz sits at the heart of the vast cross-border Portes du Soleil, which links a dozen resorts in France and Switzerland across around 600 km. It is famous for the Stash natural terrain park and access to the notorious Swiss Wall (Chavanette).', updated_at = now() WHERE slug = 'avoriaz';
UPDATE resorts SET description = 'In the sunny southern Alps near Briancon, Serre Chevalier links a string of old Hautes-Alpes villages along the Guisane valley with around 250 km of pistes rising to 2,735 m. Extensive tree-lined runs on the lower mountain and reliable sunshine define this relaxed, authentic area.', updated_at = now() WHERE slug = 'serre-chevalier';
UPDATE resorts SET description = 'A value-oriented Three Valleys resort at 1,850 m in the Belleville valley, Les Menuires offers excellent intermediate cruising plus the steep La Masse sector, one of the highest points of the 3 Vallees. Once known only for functional 1960s architecture, it has been steadily modernised.', updated_at = now() WHERE slug = 'les-menuires';
UPDATE resorts SET description = 'A charming Aravis village at around 1,100 m close to Annecy, La Clusaz spreads across five mountain massifs with roughly 125 km of pistes and a strong tradition of freestyle and cross-country skiing. Its traditional Savoyard character and proximity to Geneva make it a popular local favourite.', updated_at = now() WHERE slug = 'la-clusaz';
-- Switzerland
UPDATE resorts SET description = 'A car-free village at 1,620 m beneath the iconic 4,478 m Matterhorn, Zermatt offers Europe''s highest skiing on the Theodul Glacier and year-round snow at Matterhorn Glacier Paradise (3,883 m). Its terrain links across the border to Cervinia in Italy, and the historic Gornergrat cog railway serves classic long descents.', updated_at = now() WHERE slug = 'zermatt';
UPDATE resorts SET description = 'The main gateway to Switzerland''s vast 4 Vallees (around 410 km of pistes), Verbier sits at 1,500 m in the Valais and is world-renowned as a freeride mecca, hosting the finals of the Freeride World Tour on the Bec des Rosses. Its lively apres-ski and steep off-piste off Mont-Fort (3,330 m) attract expert skiers.', updated_at = now() WHERE slug = 'verbier';
UPDATE resorts SET description = 'A glamorous Engadine resort at 1,822 m, St. Moritz hosted the Winter Olympics twice (1928 and 1948) and claims to be the birthplace of alpine winter tourism. Set beside a frozen lake that stages polo, cricket and horse racing on snow, it offers sunny high-altitude skiing on Corviglia and the legendary Cresta Run toboggan track.', updated_at = now() WHERE slug = 'st-moritz';
UPDATE resorts SET description = 'One of Europe''s highest towns at around 1,560 m and host of the World Economic Forum, Davos in Graubunden spreads skiing across several separate areas, including the famous Parsenn with its long descents toward Klosters. It also has a deep heritage in ice sports and cross-country skiing.', updated_at = now() WHERE slug = 'davos';
UPDATE resorts SET description = 'Part of the Flims-Laax-Falera area (Weisse Arena) in Graubunden, Laax is a freestyle hotspot boasting one of the world''s largest snowparks and a big superpipe, plus around 220 km of pistes rising to the 3,018 m Vorab glacier.', updated_at = now() WHERE slug = 'laax';
UPDATE resorts SET description = 'A scenic Jungfrau-region village at around 1,034 m beneath the north face of the Eiger, Grindelwald links with Wengen and the First area across the Bernese Oberland. Reached by mountain railways and modern gondolas, it combines dramatic alpine scenery with broad, sunny skiing.', updated_at = now() WHERE slug = 'grindelwald';
UPDATE resorts SET description = 'Known as the "Pearl of the Alps," this car-free Valais village at 1,800 m is ringed by thirteen 4,000 m peaks and skis on the high Fee Glacier, giving reliable snow-sure and summer skiing. The Metro Alpin funicular serves one of the world''s highest revolving restaurants at around 3,500 m.', updated_at = now() WHERE slug = 'saas-fee';
UPDATE resorts SET description = 'A car-free Jungfrau resort at around 1,274 m reached only by cog railway, Wengen is home to the Lauberhorn, the longest and one of the most storied downhill races on the World Cup circuit. Its gentle sunny slopes and Belle Epoque hotels sit beneath the Eiger, Monch and Jungfrau.', updated_at = now() WHERE slug = 'wengen';
UPDATE resorts SET description = 'A sunny plateau resort at around 1,500 m in the Valais, Crans-Montana enjoys panoramic views over the Rhone valley and the 4,000 m peaks beyond. Long a chic destination with golf and a film festival, it offers mostly intermediate skiing rising to the Plaine Morte glacier at around 3,000 m.', updated_at = now() WHERE slug = 'crans-montana';
UPDATE resorts SET description = 'A deep-snow freeride destination near Lucerne, Engelberg (1,000 m) skis on Mount Titlis up to around 3,020 m via the world''s first rotating cable car, giving one of central Switzerland''s biggest verticals. Its Laub and Galtiberg off-piste runs are legendary among powder hunters.', updated_at = now() WHERE slug = 'engelberg';
UPDATE resorts SET description = 'A historic town at 1,444 m at a crossroads of central Switzerland, Andermatt has been transformed by major investment and now links with Sedrun and Disentis as the SkiArena Andermatt-Sedrun. The Gemsstock (2,961 m) is famed for challenging north-facing off-piste and reliable snow.', updated_at = now() WHERE slug = 'andermatt';
UPDATE resorts SET description = 'A chic Bernese Oberland destination at around 1,050 m, Gstaad spreads gentle, scenic skiing across numerous villages and mountains with roughly 200 km of pistes, plus glacier skiing at Glacier 3000. Its car-restricted promenade, luxury hotels and celebrity following define its exclusive image.', updated_at = now() WHERE slug = 'gstaad';
-- Austria
UPDATE resorts SET description = 'Widely regarded as a cradle of alpine skiing and home of one of the first ski clubs (1901), St. Anton (1,304 m) anchors the Ski Arlberg, Austria''s largest linked area with around 300 km of pistes. It is famed for demanding off-piste off the Valluga (2,811 m), the Kandahar downhill and boisterous apres-ski.', updated_at = now() WHERE slug = 'st-anton-am-arlberg';
UPDATE resorts SET description = 'A beautifully preserved medieval town at 762 m in Tyrol, Kitzbuhel hosts the Hahnenkamm''s Streif, the most feared downhill on the World Cup circuit. Its relatively low altitude is offset by strong snowmaking, and the extensive area is linked by the 3S gondola across the valley.', updated_at = now() WHERE slug = 'kitzbuehel';
UPDATE resorts SET description = 'A snow-sure Tyrolean resort at 1,377 m, Ischgl skis high in the Silvretta Arena (around 240 km of pistes) linked across the border to duty-free Samnaun in Switzerland. It is famous for its raucous party scene and its season-opening and closing pop concerts.', updated_at = now() WHERE slug = 'ischgl';
UPDATE resorts SET description = 'A high Otztal resort at 1,377 m, Solden is one of the few areas with lift-served skiing on two glaciers and access to three 3,000 m peaks (the "Big 3"). It reliably opens the Alpine Ski World Cup season each October and featured as a James Bond location in Spectre.', updated_at = now() WHERE slug = 'soelden';
UPDATE resorts SET description = 'A lively Zillertal resort at around 630 m, Mayrhofen is home to the Harakiri, at 78% gradient one of the steepest groomed pistes in Austria. Its Penken and Ahorn mountains offer strong intermediate terrain and a well-known snowpark.', updated_at = now() WHERE slug = 'mayrhofen';
UPDATE resorts SET description = 'Part of the Skicircus Saalbach Hinterglemm Leogang Fieberbrunn, one of Austria''s largest linked areas at around 270 km, this Salzburgerland resort (1,003 m) is known for a sunny, largely intermediate circuit you can ski around in a day, plus vibrant apres-ski.', updated_at = now() WHERE slug = 'saalbach-hinterglemm';
UPDATE resorts SET description = 'An upscale, snow-sure Arlberg village at around 1,450 m linked into the roughly 300 km Ski Arlberg network, Lech (with neighbouring Zurs) is known for exclusive hotels, the scenic "White Ring" circuit and a long-standing royal and celebrity clientele.', updated_at = now() WHERE slug = 'lech-am-arlberg';
UPDATE resorts SET description = 'One of Austria''s highest villages at 1,930 m in the Otztal, Obergurgl-Hochgurgl is snow-sure and family-friendly, with reliable conditions from late autumn to spring and a compact, largely intermediate area free of glacier crevasse hazards.', updated_at = now() WHERE slug = 'obergurgl';
UPDATE resorts SET description = 'A Styrian resort at 745 m on the Dachstein-Tauern''s four-mountain Ski Amade network, Schladming is renowned for its floodlit night slalom, one of the loudest events on the World Cup circuit, and hosted the 2013 Alpine World Championships.', updated_at = now() WHERE slug = 'schladming';
UPDATE resorts SET description = 'A dramatic Belle Epoque spa town at around 1,000 m built on a waterfall-lined gorge in Salzburgerland, Bad Gastein offers broad ski terrain across the Gastein valley plus thermal springs and radon healing galleries.', updated_at = now() WHERE slug = 'bad-gastein';
UPDATE resorts SET description = 'A lakeside town at 757 m paired with the Kitzsteinhorn glacier at neighbouring Kaprun, Zell am See-Kaprun combines scenic tree-lined skiing above Lake Zell with snow-sure, high-altitude glacier runs reaching around 3,000 m.', updated_at = now() WHERE slug = 'zell-am-see';
UPDATE resorts SET description = 'A quiet, snowy hamlet at 1,407 m on the Arlberg pass, Stuben is the birthplace of ski pioneer Hannes Schneider and offers access to the wider roughly 300 km Ski Arlberg network away from the crowds.', updated_at = now() WHERE slug = 'stuben-am-arlberg';
-- Italy
UPDATE resorts SET description = 'A glamorous Dolomites resort at 1,224 m ringed by dramatic pale peaks, Cortina hosted the 1956 Winter Olympics and will co-host the 2026 Games with Milan. Part of the Dolomiti Superski, it is known for the Tofana downhill, spectacular scenery and la dolce vita atmosphere.', updated_at = now() WHERE slug = 'cortina-dampezzo';
UPDATE resorts SET description = 'A Ladin-speaking valley in the Dolomites (Ortisei, Santa Cristina and Selva at around 1,240-1,560 m), Val Gardena sits on the famous Sellaronda circuit within the roughly 1,200 km Dolomiti Superski. It hosts the Saslong World Cup downhill and is renowned for its woodcarving traditions.', updated_at = now() WHERE slug = 'val-gardena';
UPDATE resorts SET description = 'A purpose-built resort at 2,035 m in the Piedmont Alps, Sestriere anchors the Via Lattea (Milky Way) linking Italian and French resorts across around 400 km. Developed by the Agnelli/Fiat family, it hosted the alpine events of the 2006 Turin Winter Olympics.', updated_at = now() WHERE slug = 'sestriere';
UPDATE resorts SET description = 'An elegant resort at 1,550 m between the Brenta Dolomites and the Adamello-Presanella glaciers, Madonna di Campiglio is famed for immaculate grooming, Sellaronda-style connections and a chic Italian apres scene; it hosts the "3Tre" World Cup night slalom.', updated_at = now() WHERE slug = 'madonna-di-campiglio';
UPDATE resorts SET description = 'A snow-sure Aosta Valley resort at 2,050 m beneath the Italian side of the Matterhorn (Monte Cervino), Cervinia offers high-altitude, mostly sunny intermediate terrain linked across the glacier to Zermatt in Switzerland, forming one of the highest and largest cross-border areas in the Alps.', updated_at = now() WHERE slug = 'breuil-cervinia';
UPDATE resorts SET description = 'A high, duty-free resort at 1,816 m near the Swiss border, Livigno is known for reliable snow, low prices on its long shopping street and strong freestyle and cross-country offerings; it will host freestyle and snowboard events at the 2026 Winter Olympics.', updated_at = now() WHERE slug = 'livigno';
UPDATE resorts SET description = 'A Ladin-speaking area of the Dolomites at around 1,300-1,600 m on the Sellaronda and Dolomiti Superski, Alta Badia is known for gentle cruising, gourmet mountain huts and the challenging Gran Risa World Cup giant slalom at La Villa.', updated_at = now() WHERE slug = 'alta-badia';
UPDATE resorts SET description = 'A historic spa town at 1,225 m in Lombardy''s Valtellina, Bormio is famed for the Stelvio, one of the toughest and most spectacular downhills on the World Cup circuit, and will host the men''s alpine speed events at the 2026 Olympics. Roman-era thermal baths add to its appeal.', updated_at = now() WHERE slug = 'bormio';
UPDATE resorts SET description = 'A stylish resort at 1,224 m on the Italian side of Mont Blanc, Courmayeur combines a charming pedestrian village with sunny slopes and world-class off-piste, including glacier descents accessed via the Skyway Monte Bianco cable car and the tunnel link to Chamonix.', updated_at = now() WHERE slug = 'courmayeur';
UPDATE resorts SET description = 'A quiet, snowy Aosta Valley resort at 1,441 m linked cross-border to La Rosiere in France as the Espace San Bernardo (around 160 km), La Thuile is known for uncrowded pistes, tree skiing and reliable snow.', updated_at = now() WHERE slug = 'la-thuile';
UPDATE resorts SET description = 'A lively Val di Fassa village at 1,465 m in the Trentino Dolomites, Canazei is a key base for the Sellaronda circuit and lies beneath the dramatic Marmolada, the highest peak of the Dolomites (3,343 m), with its long glacier descent.', updated_at = now() WHERE slug = 'canazei';
-- Germany
UPDATE resorts SET description = 'Bavaria''s premier resort at around 720 m beneath the Zugspitze (2,962 m), Germany''s highest mountain, Garmisch-Partenkirchen hosted the 1936 Winter Olympics and stages the classic Kandahar World Cup downhill and New Year ski jumping of the Four Hills Tournament. It offers glacier skiing on the Zugspitzplatt and classic runs on the Garmisch Classic area.', updated_at = now() WHERE slug = 'garmisch-partenkirchen';
UPDATE resorts SET description = 'Germany''s southernmost town at 815 m in the Allgau Alps, Oberstdorf is world-famous for ski jumping and ski flying, hosting Four Hills Tournament events, and offers varied alpine slopes on the Nebelhorn and Fellhorn/Kanzelwand areas.', updated_at = now() WHERE slug = 'oberstdorf';
-- Andorra
UPDATE resorts SET description = 'The largest ski area in the Pyrenees at around 210 km of pistes, Grandvalira stretches across the eastern Andorran valleys from Pas de la Casa to Soldeu-El Tarter, rising to about 2,640 m. It hosts Alpine World Cup finals at Soldeu and pairs snow-sure terrain with lively, tax-free resort villages.', updated_at = now() WHERE slug = 'grandvalira';
UPDATE resorts SET description = 'On the western side of Andorra, Pal Arinsal is a family-friendly Pyrenean area of around 60 km of pistes, linking the wooded Pal sector with the steeper Arinsal terrain by cable car, close to the capital Andorra la Vella.', updated_at = now() WHERE slug = 'vallnord-pal-arinsal';
-- Spain
UPDATE resorts SET description = 'Spain''s most prestigious resort at 1,500 m in the Aran Valley of the Catalan Pyrenees, Baqueira-Beret offers around 160 km of largely north-facing, snow-sure pistes across three sectors and is a long-time favourite of the Spanish royal family.', updated_at = now() WHERE slug = 'baqueira-beret';
UPDATE resorts SET description = 'Europe''s southernmost major resort, Sierra Nevada rises above Granada to around 3,300 m in Andalusia, giving long seasons into spring and rare views toward the Mediterranean and Africa. It hosted the 1996 Alpine World Championships and pairs sunny high-altitude skiing with the lively Pradollano village.', updated_at = now() WHERE slug = 'sierra-nevada';
UPDATE resorts SET description = 'A large Aragonese Pyrenees resort at around 1,500 m spread across four sunny valleys near the French border, Formigal (linked with neighbouring Panticosa) offers extensive intermediate terrain and a lively apres scene.', updated_at = now() WHERE slug = 'formigal';
-- Norway
UPDATE resorts SET description = 'Norway''s biggest ski resort, Trysil is a family-oriented, cone-shaped mountain (Trysilfjellet) with runs on all aspects, reliable cold snow and gentle, well-groomed slopes served by a ring of lifts near the Swedish border.', updated_at = now() WHERE slug = 'trysil';
UPDATE resorts SET description = 'Dubbed the "Scandinavian Alps" for its comparatively steep and varied terrain, Hemsedal is one of Norway''s largest resorts, offering above-treeline skiing, reliable cold snow and a lively winter scene between Oslo and Bergen.', updated_at = now() WHERE slug = 'hemsedal';
UPDATE resorts SET description = 'A relaxed resort on the Bergen railway line midway between Oslo and Bergen, Geilo straddles two ski areas on either side of the valley and is especially renowned for extensive cross-country trails across the Hardangervidda plateau.', updated_at = now() WHERE slug = 'geilo';
-- Sweden
UPDATE resorts SET description = 'Sweden''s leading alpine resort, Are spreads across several linked areas above a lakeside village and has hosted the Alpine World Championships (1954 and 2007) and World Cup finals. It offers the country''s biggest vertical, tree skiing, above-treeline bowls and vibrant apres.', updated_at = now() WHERE slug = 'are';
-- Finland
UPDATE resorts SET description = 'Finland''s largest and best-known resort, Levi lies above the Arctic Circle in Lapland and regularly hosts an Alpine World Cup slalom. Known for polar darkness, northern lights, floodlit runs and glass igloos, it offers gentle fell skiing and a long season.', updated_at = now() WHERE slug = 'levi';
UPDATE resorts SET description = 'A northern Finnish resort near Kuusamo with one of the longest seasons in Europe (roughly October to May), Ruka is a compact, snow-sure fell with reliable cold conditions and a strong Nordic and freestyle World Cup heritage.', updated_at = now() WHERE slug = 'ruka';
UPDATE resorts SET description = 'A Lapland fell resort with Finland''s longest slopes and one of the country''s biggest lift-served areas, Yllas is prized for its serene, low-key atmosphere, two villages on either side of the fell, northern lights and extensive cross-country trails.', updated_at = now() WHERE slug = 'yllas';
-- Bulgaria
UPDATE resorts SET description = 'A resort in the Pirin Mountains beside a historic old town at around 990 m and skiing up to about 2,600 m, Bansko offers excellent value, modern gondola access and World Cup pistes, set within a UNESCO-listed national park.', updated_at = now() WHERE slug = 'bansko';
UPDATE resorts SET description = 'Bulgaria''s oldest resort, Borovets sits at 1,350 m in the Rila Mountains beneath Musala (2,925 m), the highest peak in the Balkans, offering tree-lined runs, night skiing and a long racing heritage.', updated_at = now() WHERE slug = 'borovets';
UPDATE resorts SET description = 'One of Europe''s sunniest resorts, Pamporovo lies in the southern Rhodope Mountains at around 1,650 m and is known for gentle, beginner-friendly slopes among pine forests and a mild, sunny climate.', updated_at = now() WHERE slug = 'pamporovo';
-- Slovenia
UPDATE resorts SET description = 'A Julian Alps resort near the Austrian and Italian borders, Kranjska Gora hosts the Vitranc Cup World Cup giant slalom and lies beside the scenic Vrsic pass and the world-famous Planica ski-flying hill. Its gentle, tree-lined slopes suit families and racers alike.', updated_at = now() WHERE slug = 'kranjska-gora';
UPDATE resorts SET description = 'Slovenia''s largest ski area, on the wooded Pohorje massif directly above the city of Maribor, hosts the "Golden Fox" women''s World Cup slalom and giant slalom and offers extensive night skiing on largely intermediate terrain.', updated_at = now() WHERE slug = 'mariborsko-pohorje';
-- Poland
UPDATE resorts SET description = 'Poland''s winter capital at the foot of the Tatra Mountains, Zakopane offers skiing on Kasprowy Wierch (1,987 m) reached by a historic cable car, plus the Wielka Krokiew ski-jumping hill. Its distinctive Goral highlander culture and wooden architecture give it a unique character.', updated_at = now() WHERE slug = 'zakopane';
-- Scotland
UPDATE resorts SET description = 'Scotland''s best-known ski area, on Cairn Gorm near Aviemore in the Cairngorms National Park, rises to around 1,097 m and has long been served by a funicular railway. Conditions are weather-dependent, but good spells offer genuine high-mountain skiing in the Highlands.', updated_at = now() WHERE slug = 'cairngorm-mountain';
UPDATE resorts SET description = 'The largest ski centre in Scotland, Glenshee spreads lifts across three valleys and four mountains in the eastern Grampians, offering the country''s most extensive network of runs when snow conditions allow.', updated_at = now() WHERE slug = 'glenshee';
UPDATE resorts SET description = 'On Aonach Mor near Fort William, Nevis Range is reached by Scotland''s only mountain gondola and offers some of the country''s highest skiing terrain, including the challenging Back Corries, with views toward Ben Nevis.', updated_at = now() WHERE slug = 'nevis-range';
-- Slovakia
UPDATE resorts SET description = 'The largest and best resort in Slovakia, Jasna skis both sides of Chopok (2,024 m) in the Low Tatras with around 50 km of pistes, snow-sure north-facing slopes, freeride terrain and modern lifts; it has hosted Alpine World Cup races.', updated_at = now() WHERE slug = 'jasna';
-- Czech Republic
UPDATE resorts SET description = 'The top Czech resort, Spindleruv Mlyn lies in the Krkonose (Giant Mountains) near the Polish border and offers two main ski areas (Svaty Petr and Medvedin), night skiing and a lively town, making it the Czech Republic''s premier winter destination.', updated_at = now() WHERE slug = 'spindleruv-mlyn';
-- ============================ NORTH AMERICA ============================
-- USA
UPDATE resorts SET description = 'One of the largest single-mountain resorts in North America, Vail (village at around 2,500 m) is famous for its seven legendary Back Bowls and the high-alpine Blue Sky Basin, spanning more than 5,300 acres in Colorado''s White River National Forest. Its Bavarian-styled pedestrian village and vast intermediate terrain make it a flagship of the Epic Pass.', updated_at = now() WHERE slug = 'vail';
UPDATE resorts SET description = 'Four distinct mountains - Snowmass, Aspen Mountain (Ajax), Aspen Highlands and Buttermilk - surround the historic silver-mining town of Aspen, Colorado. The combined area ranges from Buttermilk''s Winter X Games slopes to the expert, hike-to Highland Bowl, all sharing a glamorous, culturally rich resort town.', updated_at = now() WHERE slug = 'aspen-snowmass';
UPDATE resorts SET description = 'Among the largest ski resorts in the United States, Park City Mountain (linked with the former Canyons) sits above a historic mining town near Salt Lake City, Utah, and served as a venue for the 2002 Winter Olympics. The town is also home to the Sundance Film Festival.', updated_at = now() WHERE slug = 'park-city';
UPDATE resorts SET description = 'A steep, big-mountain Wyoming resort with a vertical of around 4,139 feet served by an iconic aerial tram to Rendezvous Mountain (3,185 m), Jackson Hole is renowned for expert terrain, deep snow and the fearsome Corbet''s Couloir. The nearby town of Jackson keeps an authentic Old West character.', updated_at = now() WHERE slug = 'jackson-hole';
UPDATE resorts SET description = 'A former gold-rush town with a colourful Victorian Main Street, Breckenridge skis across five peaks of Colorado''s Tenmile Range up to around 12,998 feet, with high alpine bowls and hike-to terrain among the highest lift-served in North America. Its lively town and Epic Pass access draw big crowds.', updated_at = now() WHERE slug = 'breckenridge';
UPDATE resorts SET description = 'A towering lava-dome volcano in California''s Eastern Sierra rising to 11,053 feet, Mammoth Mountain is known for enormous snowfalls, wide-open above-treeline terrain, top-tier freestyle parks and one of the longest seasons in the U.S., often stretching into summer.', updated_at = now() WHERE slug = 'mammoth-mountain';
UPDATE resorts SET description = 'Two linked Lake Tahoe mountains (formerly Squaw Valley and Alpine Meadows) joined by a base-to-base gondola, Palisades Tahoe hosted the 1960 Winter Olympics. It is famed for steep, rocky expert terrain, big cliffs and a rich freeski legacy.', updated_at = now() WHERE slug = 'palisades-tahoe';
UPDATE resorts SET description = 'Straddling the California-Nevada state line above South Lake Tahoe, Heavenly offers sweeping views over the lake and the high desert, a large 4,800-acre area and a vertical of around 3,500 feet, with skiing that literally crosses between two states.', updated_at = now() WHERE slug = 'heavenly';
UPDATE resorts SET description = 'A Colorado resort famed for its trademarked "Champagne Powder" and excellent tree (glade) skiing on Mount Werner, Steamboat retains a genuine ranching-town character and has produced more Winter Olympians than almost anywhere in the U.S., earning the nickname "Ski Town, USA."', updated_at = now() WHERE slug = 'steamboat';
UPDATE resorts SET description = 'Set in a dramatic box canyon in Colorado''s San Juan Mountains, Telluride pairs a beautifully preserved Victorian mining town with a modern mountain village linked by a free gondola. Its terrain ranges from gentle groomers to steep, hike-to expert chutes amid spectacular scenery.', updated_at = now() WHERE slug = 'telluride';
UPDATE resorts SET description = 'One of the largest ski areas in the U.S., Big Sky in Montana is crowned by the steep, exposed Lone Peak (3,403 m), reached by a tram, and offers big vertical, uncrowded slopes and expert couloirs across a vast, high-mountain area.', updated_at = now() WHERE slug = 'big-sky';
UPDATE resorts SET description = 'Nicknamed "The Beast of the East," Killington is the largest ski area in Vermont, spread across six peaks with a long season boosted by extensive snowmaking. It regularly hosts a women''s World Cup slalom and giant slalom on Superstar over Thanksgiving weekend.', updated_at = now() WHERE slug = 'killington';
UPDATE resorts SET description = 'A classic New England resort on Mount Mansfield (1,340 m), Vermont''s highest peak, Stowe pairs challenging "Front Four" expert trails with a charming historic village. It is one of the oldest and most storied ski destinations in the eastern U.S.', updated_at = now() WHERE slug = 'stowe';
UPDATE resorts SET description = 'A steep, deep resort in Little Cottonwood Canyon near Salt Lake City, Snowbird is renowned for enormous quantities of dry Utah powder, a vertical of around 2,900 feet and an aerial tram to Hidden Peak (3,353 m), with one of the longest seasons in the country.', updated_at = now() WHERE slug = 'snowbird';
UPDATE resorts SET description = 'A skier-only Utah institution in Little Cottonwood Canyon, Alta is famous for abundant light, dry powder and a no-frills, tradition-bound culture; it neighbours and can be combined with Snowbird to form one of the largest terrain areas in the U.S.', updated_at = now() WHERE slug = 'alta';
UPDATE resorts SET description = 'A luxury, skier-only resort above Park City, Utah, Deer Valley is renowned for impeccable grooming, limited daily lift tickets, gourmet dining and top-tier service, and hosted freestyle mogul and aerial events at the 2002 Olympics.', updated_at = now() WHERE slug = 'deer-valley';
UPDATE resorts SET description = 'A refined, purpose-built Colorado resort next to Vail, Beaver Creek is known for meticulous grooming, escalators to the slopes and family-friendly amenities, as well as the demanding Birds of Prey World Cup downhill on Golden Eagle.', updated_at = now() WHERE slug = 'beaver-creek';
UPDATE resorts SET description = 'A family-friendly Colorado resort near Dillon, Keystone spans three interconnected mountains and offers some of the most extensive night skiing in the U.S., plus above-treeline bowls and hike- or snowcat-served terrain on the Independence and Bergman bowls.', updated_at = now() WHERE slug = 'keystone';
UPDATE resorts SET description = 'A Colorado resort near Frisco with terrain naturally divided by difficulty - from gentle beginner slopes on one side to expert on the other - Copper Mountain serves as a U.S. Ski Team training base and offers high alpine bowls above the treeline.', updated_at = now() WHERE slug = 'copper-mountain';
UPDATE resorts SET description = 'Colorado''s longest continuously operated resort, owned by the city of Denver and reachable by ski train, Winter Park spans several mountains including Mary Jane, famed for its steep, relentless mogul runs, plus the high Vasquez Cirque.', updated_at = now() WHERE slug = 'winter-park';
UPDATE resorts SET description = 'America''s first destination ski resort, opened in 1936 in Idaho and credited with the world''s first chairlift, Sun Valley skis the smooth, consistent slopes of Bald Mountain ("Baldy") and retains a glamorous Hollywood-era heritage.', updated_at = now() WHERE slug = 'sun-valley';
UPDATE resorts SET description = 'A steep, high resort in New Mexico''s Sangre de Cristo Mountains rising to around 3,600 m, Taos is renowned for demanding expert terrain, ridge hikes to Kachina Peak and a distinctive Southwestern character; it was famously one of the last U.S. resorts to admit snowboarders.', updated_at = now() WHERE slug = 'taos-ski-valley';
UPDATE resorts SET description = 'A dormant stratovolcano in central Oregon rising to 9,065 feet, Mt. Bachelor offers 360-degree skiing from its summit, wide-open bowls, abundant snowfall and one of the longest seasons in the Pacific Northwest.', updated_at = now() WHERE slug = 'mt-bachelor';
UPDATE resorts SET description = 'Washington''s largest ski resort, Crystal Mountain sits in the Cascades near Mount Rainier, offering big vertical, above-treeline bowls and a gondola with spectacular views of Rainier from its summit restaurant.', updated_at = now() WHERE slug = 'crystal-mountain';
UPDATE resorts SET description = 'A Cascades resort on the crest of the mountains within easy reach of Seattle, Stevens Pass offers reliable snowfall, extensive night skiing and terrain on both the front side and the more advanced back (Mill Valley) side.', updated_at = now() WHERE slug = 'stevens-pass';
UPDATE resorts SET description = 'The Olympic mountain of the 1980 Lake Placid Winter Games, Whiteface in New York''s Adirondacks has the greatest vertical drop in the eastern U.S. (around 3,430 feet) and a reputation for challenging, exposed terrain and cold conditions.', updated_at = now() WHERE slug = 'whiteface';
UPDATE resorts SET description = 'A Vermont resort spanning Lincoln Peak and Mount Ellen in the Mad River Valley, Sugarbush offers varied classic New England terrain, steep glades and a laid-back, community-oriented atmosphere.', updated_at = now() WHERE slug = 'sugarbush';
UPDATE resorts SET description = 'A Utah resort near Ogden with luxurious day lodges, Snowbasin hosted the downhill, super-G and combined events of the 2002 Winter Olympics and offers big, uncrowded terrain with gondola and tram access.', updated_at = now() WHERE slug = 'snowbasin';
UPDATE resorts SET description = 'A laid-back resort in Big Cottonwood Canyon near Salt Lake City, Brighton is popular with locals and freestylers for its abundant Utah snow, extensive night skiing and beginner-friendly, no-attitude vibe.', updated_at = now() WHERE slug = 'brighton';
UPDATE resorts SET description = 'The largest ski area on Oregon''s Mount Hood, Mt. Hood Meadows offers varied terrain and reliable snowfall on the southeast flank of the 11,239-foot volcano, with a long season and lift-served bowls and glades.', updated_at = now() WHERE slug = 'mt-hood-meadows';
UPDATE resorts SET description = 'Idaho''s biggest ski resort, Schweitzer overlooks Lake Pend Oreille in the state''s Panhandle, offering two large open bowls, tree skiing and expansive views across three states and into Canada.', updated_at = now() WHERE slug = 'schweitzer';
UPDATE resorts SET description = 'A high-altitude Colorado resort known as "The Legend," Arapahoe Basin tops out above 13,000 feet with steep, exposed terrain like the East Wall and Montezuma Bowl and boasts one of the longest seasons in North America, often lasting into June.', updated_at = now() WHERE slug = 'arapahoe-basin';
-- Canada
UPDATE resorts SET description = 'The largest ski resort in North America, Whistler Blackcomb spans two mile-high mountains linked by the record-setting Peak 2 Peak Gondola, with more than 8,000 acres of terrain. Host of the 2010 Winter Olympic alpine and sliding events, it combines glaciers, bowls and a bustling pedestrian village in British Columbia.', updated_at = now() WHERE slug = 'whistler-blackcomb';
UPDATE resorts SET description = 'High on the Continental Divide within Banff National Park, Sunshine Village straddles the Alberta-British Columbia border at a base of around 2,160 m, capturing abundant natural snow and offering the challenging Delirium Dive among its wide alpine bowls.', updated_at = now() WHERE slug = 'banff-sunshine';
UPDATE resorts SET description = 'One of Canada''s largest ski areas, set amid the iconic scenery of Banff National Park, Lake Louise offers terrain on multiple faces with a big vertical, front-side groomers and expansive back bowls, and regularly opens the World Cup speed season.', updated_at = now() WHERE slug = 'lake-louise';
UPDATE resorts SET description = 'Home to the greatest lift-served vertical in North America (around 1,713 m), Revelstoke Mountain Resort in British Columbia is a magnet for deep-snow skiers, combining lift, cat and heli access on a single mountain with famously abundant Interior BC powder.', updated_at = now() WHERE slug = 'revelstoke';
UPDATE resorts SET description = 'The premier resort of eastern Canada, Mont-Tremblant rises above a colourful pedestrian village in Quebec''s Laurentians and offers varied terrain on multiple faces, extensive snowmaking and a lively European-style base at the foot of the hill.', updated_at = now() WHERE slug = 'mont-tremblant';
UPDATE resorts SET description = 'British Columbia''s second-largest ski area, Sun Peaks spreads across three mountains above a sunny ski-in/ski-out village near Kamloops, offering abundant dry Interior snow, long groomers and gladed tree skiing.', updated_at = now() WHERE slug = 'sun-peaks';
UPDATE resorts SET description = 'A British Columbia resort near Kelowna celebrated for its light "Champagne Powder" and its ghostly snow-covered trees ("snow ghosts"), Big White is a large, ski-in/ski-out family destination high in the Okanagan.', updated_at = now() WHERE slug = 'big-white';
UPDATE resorts SET description = 'A steep, advanced-oriented resort near Golden, British Columbia, Kicking Horse rises via gondola to around 2,450 m and is renowned for its big vertical and dozens of inbounds chutes accessed from four alpine bowls.', updated_at = now() WHERE slug = 'kicking-horse';
UPDATE resorts SET description = 'A legendary powder resort in the BC Rockies, Fernie sits below five vast alpine bowls that funnel huge Interior snowfalls, paired with a historic mining town that gives it genuine character.', updated_at = now() WHERE slug = 'fernie';
UPDATE resorts SET description = 'A resort near Quebec City with a big eastern vertical and terrain on three sides, Mont-Sainte-Anne offers extensive night skiing, world-class mountain-biking heritage in summer and sweeping views over the St. Lawrence River.', updated_at = now() WHERE slug = 'mont-sainte-anne';
UPDATE resorts SET description = 'Ontario''s largest ski resort, Blue Mountain sits on the Niagara Escarpment above the shores of Georgian Bay near Collingwood, offering extensive snowmaking, night skiing and a lively pedestrian village within easy reach of Toronto.', updated_at = now() WHERE slug = 'blue-mountain';
-- ============================ ASIA ============================
-- Japan
UPDATE resorts SET description = 'Hokkaido''s powder capital, Niseko United links four interconnected resorts (Grand Hirafu, Hanazono, Niseko Village and Annupuri) on Mount Niseko-Annupuri. Fed by Siberian storms across the Sea of Japan, it receives some of the deepest, driest snow on earth and offers famous "gate" access to backcountry terrain.', updated_at = now() WHERE slug = 'niseko-united';
UPDATE resorts SET description = 'A Nagano valley of ten linked resorts beneath the steep Northern Japan Alps, Hakuba hosted many alpine, ski-jumping and Nordic events of the 1998 Winter Olympics. It offers Japan''s biggest lift-served vertical terrain and abundant, reliable snowfall.', updated_at = now() WHERE slug = 'hakuba-valley';
UPDATE resorts SET description = 'A central Hokkaido resort known for consistently dry powder and well-groomed slopes, Furano has hosted numerous World Cup events and offers quieter, uncrowded skiing plus a scenic town in the heart of the island.', updated_at = now() WHERE slug = 'furano';
UPDATE resorts SET description = 'A Hokkaido resort spread across three mountains near Lake Toya, Rusutsu is famed for excellent tree runs through birch and pine and abundant light powder, paired with an unusually elaborate, amusement-park-style resort complex.', updated_at = now() WHERE slug = 'rusutsu';
UPDATE resorts SET description = 'Japan''s largest connected ski area, Shiga Kogen in the Nagano highlands links around 18 interconnected resorts on a single pass, hosted events at the 1998 Olympics and lies within a UNESCO biosphere reserve near the famous "snow monkey" hot springs.', updated_at = now() WHERE slug = 'shiga-kogen';
UPDATE resorts SET description = 'A historic hot-spring (onsen) village in Nagano with narrow streets and free public baths, Nozawa Onsen offers a big single-mountain vertical, deep snow and centuries of tradition, including the spectacular Dosojin fire festival.', updated_at = now() WHERE slug = 'nozawa-onsen';
UPDATE resorts SET description = 'One of Japan''s oldest ski regions, Myoko Kogen in Niigata is renowned for extremely heavy snowfall, several linked resorts, old-school charm and abundant hot springs at the base of the Myoko volcano.', updated_at = now() WHERE slug = 'myoko-kogen';
UPDATE resorts SET description = 'A Yamagata resort famous for its "snow monsters" (juhyo) - trees encased in wind-driven frost and rime - Zao Onsen combines extensive tree-lined skiing with a historic hot-spring village and dramatic frozen scenery.', updated_at = now() WHERE slug = 'zao-onsen';
UPDATE resorts SET description = 'A Tohoku resort in Iwate celebrated for long, well-groomed cruising runs and quality powder on north-facing slopes, Appi Kogen offers a modern, uncrowded and family-friendly experience.', updated_at = now() WHERE slug = 'appi-kogen';
UPDATE resorts SET description = 'A large Niigata resort linked to neighbouring Kagura by the Dragondola, one of the world''s longest gondolas, Naeba offers extensive, snow-sure terrain within easy reach of Tokyo by bullet train.', updated_at = now() WHERE slug = 'naeba';
-- South Korea
UPDATE resorts SET description = 'Korea''s largest ski resort, Yongpyong ("Dragon Valley") in Gangwon Province hosted the alpine technical events of the 2018 PyeongChang Winter Olympics and offers the country''s longest runs plus extensive night skiing.', updated_at = now() WHERE slug = 'yongpyong';
UPDATE resorts SET description = 'A large resort in Gangwon Province built around a former coal-mining area, High1 combines skiing with a major casino and hotel complex, offering wide, well-groomed slopes and reliable snowmaking.', updated_at = now() WHERE slug = 'high1';
-- China
UPDATE resorts SET description = 'One of China''s largest and oldest ski resorts, Yabuli in Heilongjiang Province hosted the 1996 Asian Winter Games and remains a key training base and destination in the country''s far northeast.', updated_at = now() WHERE slug = 'yabuli';
UPDATE resorts SET description = 'A popular resort in the Chongli district near Zhangjiakou - part of the region that hosted snow events for the 2022 Beijing Winter Olympics - Wanlong is known for good-quality snow and some of the best-developed pistes within reach of Beijing.', updated_at = now() WHERE slug = 'wanlong';
-- ============================ SOUTH AMERICA ============================
-- Chile
UPDATE resorts SET description = 'Set at around 3,000 m in the Andes some 46 km from Santiago, Valle Nevado is a modern, French-designed resort opened in 1988 and the largest in the Tres Valles domain, which links with La Parva and El Colorado to form the biggest skiable area in South America. It is known for reliable dry powder, sunny high-altitude slopes and heliskiing, with a season running roughly June to October.', updated_at = now() WHERE slug = 'valle-nevado';
UPDATE resorts SET description = 'One of the oldest and most iconic resorts in South America, Portillo sits at 2,880 m beside the emerald Laguna del Inca high in the Chilean Andes near the Argentine border. Its landmark yellow Hotel Portillo, unique va-et-vient "slingshot" lifts and steep off-piste have long made it a training base for Northern Hemisphere national teams.', updated_at = now() WHERE slug = 'portillo';
UPDATE resorts SET description = 'An Andean resort at around 2,750 m near Santiago and popular with Chilean locals, La Parva forms part of the Tres Valles alongside El Colorado and Valle Nevado, offering sunny slopes, chalet-style residences and access to extensive off-piste terrain.', updated_at = now() WHERE slug = 'la-parva';
UPDATE resorts SET description = 'A resort on the flanks of the Nevados de Chillan volcano in central Chile, it is known for natural thermal springs, tree skiing and one of the longest runs in South America, the roughly 13 km "Las Tres Marias."', updated_at = now() WHERE slug = 'nevados-de-chillan';
-- Argentina
UPDATE resorts SET description = 'The largest and most developed ski resort in South America, Cerro Catedral rises above Bariloche in Patagonia''s Lake District, offering extensive terrain, dramatic granite spires and sweeping views over Lake Nahuel Huapi, along with a lively base village.', updated_at = now() WHERE slug = 'cerro-catedral';
UPDATE resorts SET description = 'A high Andes resort in Mendoza Province renowned across the Southern Hemisphere for steep, vast off-piste terrain, Las Lenas is famed for the Marte chairlift, which unlocks a huge expanse of expert backcountry couloirs and bowls.', updated_at = now() WHERE slug = 'las-lenas';
UPDATE resorts SET description = 'A scenic Patagonian resort near San Martin de los Andes in Neuquen, Chapelco offers well-groomed slopes descending through lenga forest with panoramic views over Lake Lacar and the surrounding Andes.', updated_at = now() WHERE slug = 'chapelco';
UPDATE resorts SET description = 'The world''s southernmost ski resort, near Ushuaia in Tierra del Fuego, Cerro Castor benefits from low-elevation, snow-sure conditions and one of the longest seasons in the Southern Hemisphere, hosting many Northern Hemisphere teams for training.', updated_at = now() WHERE slug = 'cerro-castor';
-- ============================ OCEANIA ============================
-- Australia
UPDATE resorts SET description = 'In the Snowy Mountains of New South Wales, Thredbo has Australia''s longest runs and greatest vertical (around 672 m), descending from near Mount Kosciuszko through a village set in a steep valley, with a lively alpine atmosphere.', updated_at = now() WHERE slug = 'thredbo';
UPDATE resorts SET description = 'The largest ski resort in the Southern Hemisphere, Perisher combines four linked areas (Perisher Valley, Blue Cow, Smiggin Holes and Guthega) in Kosciuszko National Park, New South Wales, served by a large lift network and a mountain railway.', updated_at = now() WHERE slug = 'perisher';
UPDATE resorts SET description = 'Victoria''s most accessible major resort, within around three hours of Melbourne, Mt Buller offers a large lift network around a village near the summit, with varied terrain and strong snowmaking.', updated_at = now() WHERE slug = 'mt-buller';
UPDATE resorts SET description = 'An alpine village resort in Victoria with ski-in/ski-out accommodation, Falls Creek offers the state''s most extensive terrain, strong snowmaking and excellent cross-country trails across the Bogong High Plains.', updated_at = now() WHERE slug = 'falls-creek';
UPDATE resorts SET description = 'The highest ski resort in Victoria, Mt Hotham is unusual in that its village sits along the summit ridge, so runs descend away from the accommodation. It is known for good natural snow, tree skiing and a reputation for powder.', updated_at = now() WHERE slug = 'mt-hotham';
-- New Zealand
UPDATE resorts SET description = 'Queenstown''s closest ski field, Coronet Peak is famous for night skiing and sweeping views over Lake Wakatipu, with predominantly intermediate terrain, extensive snowmaking and a high-energy atmosphere close to the resort town.', updated_at = now() WHERE slug = 'coronet-peak';
UPDATE resorts SET description = 'Set in the dramatic mountain range that gives it its name above Queenstown, The Remarkables offers sunny bowls, good beginner and intermediate terrain and access to steeper chutes like Homeward Bound, amid spectacular alpine scenery.', updated_at = now() WHERE slug = 'the-remarkables';
UPDATE resorts SET description = 'Between Wanaka and Queenstown, Cardrona is New Zealand''s leading freestyle and terrain-park destination, hosting World Cup and Games qualifying events, with wide, sunny basins and a long season boosted by snowmaking.', updated_at = now() WHERE slug = 'cardrona';
UPDATE resorts SET description = 'The largest ski field on New Zealand''s South Island, Treble Cone above Lake Wanaka is prized for its steep, challenging terrain, long descents and stunning views, making it a favourite of advanced skiers.', updated_at = now() WHERE slug = 'treble-cone';
UPDATE resorts SET description = 'A Canterbury resort with the longest season in New Zealand, Mt Hutt rises high above the Canterbury Plains, offering wide-open terrain, reliable snow and views to the Southern Alps and, on clear days, the Pacific.', updated_at = now() WHERE slug = 'mt-hutt';
-- ============================ MIDDLE EAST / CAUCASUS / SOUTH ASIA ============================
-- Turkey
UPDATE resorts SET description = 'Turkey''s most famous resort, on Mount Uludag (2,543 m) rising above the city of Bursa, offers hotel-lined ski-in/ski-out slopes among fir forests within easy reach of Istanbul, making it the country''s most popular winter destination.', updated_at = now() WHERE slug = 'uludag';
UPDATE resorts SET description = 'A high-altitude resort on the slopes above Erzurum in eastern Turkey rising to around 3,100 m, Palandoken boasts some of the country''s steepest and longest runs and dry, reliable snow; it hosted the 2011 Winter Universiade.', updated_at = now() WHERE slug = 'palandoken';
UPDATE resorts SET description = 'A modern, extensively developed resort on the slopes of Mount Erciyes, a dormant volcano near Kayseri in central Anatolia rising to over 3,900 m, Erciyes offers wide pistes, good snow and easy access.', updated_at = now() WHERE slug = 'erciyes';
-- Georgia
UPDATE resorts SET description = 'A high Caucasus resort at around 2,200 m on the Georgian Military Highway north of Tbilisi, Gudauri is above the treeline, snow-sure and increasingly popular for freeride and heliskiing thanks to its wide open terrain and affordable prices.', updated_at = now() WHERE slug = 'gudauri';
UPDATE resorts SET description = 'A historic resort in the Lesser Caucasus set among pine forests at around 1,700 m, Bakuriani offers gentle, family-friendly slopes and a long winter-sports tradition; it co-hosted the 2023 Freestyle and Snowboard World Championships.', updated_at = now() WHERE slug = 'bakuriani';
-- Iran
UPDATE resorts SET description = 'One of the highest ski resorts in the world, Dizin lies in the Alborz Mountains north of Tehran with lifts reaching around 3,600 m. It offers reliable dry powder, a long season and wide, mostly intermediate terrain.', updated_at = now() WHERE slug = 'dizin';
UPDATE resorts SET description = 'One of Iran''s best-known resorts, Shemshak in the Alborz Mountains near Tehran is known for steeper, more challenging terrain than nearby Dizin and popular night skiing, making it a favourite of advanced local skiers.', updated_at = now() WHERE slug = 'shemshak';
-- India
UPDATE resorts SET description = 'A Himalayan resort in Kashmir, Gulmarg is served by one of the world''s highest cable cars, rising to around 3,980 m on Apharwat Peak. It is legendary among expert skiers for vast, ungroomed high-altitude powder and backcountry terrain.', updated_at = now() WHERE slug = 'gulmarg';
UPDATE resorts SET description = 'A resort in Uttarakhand''s Garhwal Himalayas at around 2,500-3,000 m, Auli offers well-groomed slopes with spectacular views of Nanda Devi, one of India''s highest peaks, and is reached by a long cable car from Joshimath.', updated_at = now() WHERE slug = 'auli';
-- Lebanon
UPDATE resorts SET description = 'The largest ski resort in the Middle East, Mzaar Kfardebian (Faraya) lies in Mount Lebanon around 50 km from Beirut, with terrain rising to about 2,465 m. Its sunny slopes famously allow skiing in the morning and a Mediterranean beach in the afternoon.', updated_at = now() WHERE slug = 'mzaar-kfardebian';
-- ============================ V4 ADDITIONS ============================
-- Chile
UPDATE resorts SET description = 'A Farellones-based resort at around 2,430 m and part of the Tres Valles near Santiago, El Colorado links with La Parva and Valle Nevado to form the largest skiable domain in South America. It offers wide, sunny slopes and, as the closest major area to the Chilean capital, easy access.', updated_at = now() WHERE slug = 'el-colorado';
UPDATE resorts SET description = 'Set on the slopes of the Lonquimay volcano amid ancient araucaria (monkey-puzzle) forests in Chile''s Araucania region, Corralco is a modern resort known for abundant snowfall, volcanic scenery and uncrowded, tree-lined terrain.', updated_at = now() WHERE slug = 'corralco';
UPDATE resorts SET description = 'A resort on the Casablanca volcano within Puyehue National Park in southern Chile, Antillanca is known for forested runs, views over surrounding lakes and volcanoes, and volcano ski-touring above the lifts.', updated_at = now() WHERE slug = 'antillanca';
-- Argentina
UPDATE resorts SET description = 'A Neuquen resort beside the Copahue volcano and its crater lakes in northern Patagonia, Caviahue offers araucaria-lined slopes, nearby thermal springs and a quiet, family-friendly atmosphere.', updated_at = now() WHERE slug = 'caviahue';
UPDATE resorts SET description = 'A boutique resort above Villa La Angostura in Argentine Patagonia, Cerro Bayo offers uncrowded slopes descending toward sweeping views over Lake Nahuel Huapi, with a relaxed, scenic character.', updated_at = now() WHERE slug = 'cerro-bayo';
UPDATE resorts SET description = 'A sunny, snow-sure resort near Esquel in Argentina''s Chubut Province, La Hoya sits in a largely south-facing cirque that holds snow well, giving it a long season and a reputation for good value and light powder.', updated_at = now() WHERE slug = 'la-hoya';
UPDATE resorts SET description = 'A Mendoza resort on the international highway toward Aconcagua, the highest peak in the Americas, Los Penitentes offers terrain on both sides of the valley in a stark, high-Andes setting near the Chilean border.', updated_at = now() WHERE slug = 'los-penitentes';
-- Europe
UPDATE resorts SET description = 'A Bauhaus-inspired, purpose-built and snow-sure resort at 1,600 m at the heart of the Grand Massif above the Arve valley in Haute-Savoie, Flaine offers a large, mostly intermediate area, a striking modernist village and views of Mont Blanc.', updated_at = now() WHERE slug = 'flaine';
UPDATE resorts SET description = 'A traditional Haute-Savoie market town at around 1,000 m at the centre of the vast cross-border Portes du Soleil, Morzine combines authentic Alpine charm with easy access to a dozen linked resorts and around 600 km of pistes spanning France and Switzerland.', updated_at = now() WHERE slug = 'morzine';
-- North America
UPDATE resorts SET description = 'A Colorado resort widely regarded as a birthplace of extreme skiing, Crested Butte is famed for steep, ungroomed expert terrain like the Extreme Limits, paired with a colourful, well-preserved Victorian mining town at the end of the valley.', updated_at = now() WHERE slug = 'crested-butte';
-- Asia
UPDATE resorts SET description = 'A snow-heavy Hokkaido resort west of Sapporo, Kiroro is famed for exceptionally deep, dry powder and one of the longest seasons in Japan, with two peaks offering long groomers and abundant tree skiing.', updated_at = now() WHERE slug = 'kiroro';
